### ISSUE TITLE
MBTopAppBar broken without NavIcon

### ISSUE THREAD

**Issue by Xenoage** [Material-Blazor/Material.Blazor#395]
`<MBTopAppBar Title="Test" NavIcon="menu">
</MBTopAppBar>`

works, but

`<MBTopAppBar Title="Test">
</MBTopAppBar>`

does not. Error in console:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Material.Blazor.IconMI.get_Text()
   at Material.Blazor.MBIconHelper.get_Text()
   at Material.Blazor.MBIcon.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by Xenoage** [comment]
Same problem for a `MBIconButton` without an `Icon` attribute.

**Comment by stefanloerwald** [comment]
I've just added a PR for this. I think it makes sense for MBIconButton to throw for missing an Icon, because by its very definition, an icon should be used for an icon button. For `MBTopAppBar`, of course it's different, because an AppBar without NavIcon is perfectly fine.

**Comment by Xenoage** [comment]
Great, thanks. For `MBIconButton`, maybe a default value would be preferable? Or at least a meaningful exception instead of just a `NullReferenceException` in the renderer?
